//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiceRoller.Translations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiceRoller.Translations.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d10.
        /// </summary>
        internal static string d10 {
            get {
                return ResourceManager.GetString("d10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d100.
        /// </summary>
        internal static string d100 {
            get {
                return ResourceManager.GetString("d100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d12.
        /// </summary>
        internal static string d12 {
            get {
                return ResourceManager.GetString("d12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d20.
        /// </summary>
        internal static string d20 {
            get {
                return ResourceManager.GetString("d20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d4.
        /// </summary>
        internal static string d4 {
            get {
                return ResourceManager.GetString("d4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d6.
        /// </summary>
        internal static string d6 {
            get {
                return ResourceManager.GetString("d6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d8.
        /// </summary>
        internal static string d8 {
            get {
                return ResourceManager.GetString("d8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        internal static string Roll {
            get {
                return ResourceManager.GetString("Roll", resourceCulture);
            }
        }
    }
}
